# Generated by Django 6.0 on 2026-01-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lessoncontent_created_at_lessoncontent_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessontask',
            name='external_task_uuid',
        ),
        migrations.RemoveField(
            model_name='lessontask',
            name='id',
        ),
        migrations.AddField(
            model_name='lessontask',
            name='task_uuid',
            field=models.UUIDField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessontask',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
