# Generated by Django 6.0 on 2026-03-18 18:50

import apps.lessons.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_lessontask_external_task_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='file',
            field=models.FileField(max_length=500, storage=apps.lessons.storage.LessonContentS3Storage(), upload_to=''),
        ),
    ]
