# Generated by Django 6.0 on 2026-04-06 16:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lessoncontent_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontask',
            name='task_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
