# Generated by Django 6.0 on 2026-04-06 17:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0005_alter_lessontask_task_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessontask",
            name="task_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="lessontask",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
