services:
  # ----------- INFRASTRUCTURE -----------
  postgres:
    image: postgres:17
    container_name: postgres-main
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      USERS_DB_NAME: ${USERS_DB_NAME}
      USERS_DB_USER: ${USERS_DB_USER}
      USERS_DB_PASSWORD: ${USERS_DB_PASSWORD}
      COURSES_DB_NAME: ${COURSES_DB_NAME}
      COURSES_DB_USER: ${COURSES_DB_USER}
      COURSES_DB_PASSWORD: ${COURSES_DB_PASSWORD}
      TASKS_DB_NAME: ${TASKS_DB_NAME}
      TASKS_DB_USER: ${TASKS_DB_USER}
      TASKS_DB_PASSWORD: ${TASKS_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 7
    restart: unless-stopped
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:8
    container_name: redis-main
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
  
  minio:
    image: minio/minio:latest
    container_name: minio-main
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Сервис для создания бакета
  createbuckets:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./create-bucket.sh:/create-bucket.sh
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        chmod +x /create-bucket.sh &&
        /create-bucket.sh
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    restart: "no"


  # ---------- SANDBOX BUILDER -----------
  sandbox-builder:
    build:
      context: ./services/tasks/app/sandbox/docker/python
      dockerfile: Dockerfile
    image: sandbox-python:latest
    container_name: sandbox-builder
    restart: "no"


  # ----------- MICROSERVICES ------------
  users-service:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    container_name: users-service
    environment:
      DATABASE__DB_HOST: postgres
      DATABASE__DB_PORT: 5432
      DATABASE__DB_NAME: ${USERS_DB_NAME}
      DATABASE__DB_USER: ${USERS_DB_USER}
      DATABASE__DB_PASSWORD: ${USERS_DB_PASSWORD}
      REDIS__REDIS_HOST: redis
      REDIS__REDIS_PORT: 6379
    expose:
      - "8001"
    # ports:
    #   - "8001:8000"
    volumes:
      - ./services/users/:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 8s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  courses-service:
    build:
      context: ./services/courses
      dockerfile: Dockerfile
    container_name: courses-service
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      SECRET_KEY: ${COURSES_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,courses-service,nginx,api-gateway
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${COURSES_DB_NAME}
      DB_USER: ${COURSES_DB_USER}
      DB_PASSWORD: ${COURSES_DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      S3_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      S3_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_ENDPOINT_URL: http://minio:9000
      S3_PUBLIC_URL: http://localhost:9000
      S3_REGION: us-east-1
      MAX_FILE_SIZE_MB: ${COURSES_MAX_FILE_SIZE_MB}
      USERS_SERVICE_URL: ${USERS_SERVICE_URL}
    expose:
      - "8002"
    # ports:
    #   - "8002:8000"
    volumes:
      - ./services/courses/:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      users-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 8s
      timeout: 8s
      retries: 5
    restart: unless-stopped

  courses-listener:
    build:
      context: ./services/courses
      dockerfile: Dockerfile
    container_name: courses-listener
    command: python manage.py run_event_listener
    environment:
      SECRET_KEY: ${COURSES_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,courses-service,nginx,api-gateway
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${COURSES_DB_NAME}
      DB_USER: ${COURSES_DB_USER}
      DB_PASSWORD: ${COURSES_DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      courses-service:
        condition: service_healthy
    restart: unless-stopped

  tasks-service:
    build:
      context: ./services/tasks
      dockerfile: Dockerfile
    container_name: tasks-service
    environment:
      DATABASE__DB_HOST: postgres
      DATABASE__DB_PORT: 5432
      DATABASE__DB_NAME: ${TASKS_DB_NAME}
      DATABASE__DB_USER: ${TASKS_DB_USER}
      DATABASE__DB_PASSWORD: ${TASKS_DB_PASSWORD}
      REDIS__REDIS_HOST: redis
      REDIS__REDIS_PORT: 6379
      S3__S3_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      S3__S3_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      S3__S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3__S3_ENDPOINT_URL: http://minio:9000
      S3__S3_REGION: us-east-1
      USER_SERVICE_URL: ${USERS_SERVICE_URL}
      COURSE_SERVICE_URL: ${COURSES_SERVICE_URL}
      # Переменная для docker.from_env() (указываю явно, но это не обязательно)
      DOCKER_HOST: unix:///var/run/docker.sock
    expose:
      - "8003"
    # ports:
    #   - "8003:8000"
    volumes:
      - ./services/tasks/:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      users-service:
        condition: service_healthy
      courses-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 8s
      timeout: 8s
      retries: 8
    restart: unless-stopped

  nginx:
    image: nginx:1.29.6-alpine
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - users-service
      - courses-service
      - tasks-service
      # - frontend
    restart: unless-stopped


volumes:
  postgres_data:
  redis_data:
  minio_data: