"""prod migration

Revision ID: 24ec7a0cd71f
Revises: 65e3dc2214b8
Create Date: 2026-03-12 20:25:25.293918

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24ec7a0cd71f"
down_revision: Union[str, Sequence[str], None] = "65e3dc2214b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "task_type",
            sa.Enum("TEST", "FILE_UPLOAD", "SANDBOX", name="tasktype"),
            nullable=False,
        ),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tasks_lesson_id"), "tasks", ["lesson_id"], unique=False
    )
    op.create_table(
        "code_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("template_code", sa.String(), nullable=False),
        sa.Column("tests_definition", sa.String(), nullable=False),
        sa.Column("time_limit", sa.Integer(), nullable=False),
        sa.Column("memory_limit", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_code_tasks_task_id"), "code_tasks", ["task_id"], unique=True
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "SINGLE_CHOIE",
                "MULTIPLE_CHOICE",
                "SHORT_ANSWER",
                name="questiontype",
            ),
            nullable=False,
        ),
        sa.Column("correct_answers", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_questions_order"), "questions", ["order"], unique=False
    )
    op.create_index(
        op.f("ix_questions_task_id"), "questions", ["task_id"], unique=False
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "PASSED",
                "FAILED",
                "NEEDS_REVIEW",
                name="submissionstatus",
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("max_score", sa.Integer(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("feedback", sa.JSON(), nullable=True),
        sa.Column("s3_file_key", sa.String(length=500), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submissions_created_at"),
        "submissions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_submissions_status"), "submissions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_submissions_task_id"),
        "submissions",
        ["task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_submissions_user_id"),
        "submissions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "answer_options",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"], ["questions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_answer_options_question_id"),
        "answer_options",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("mentor_id", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submissions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reviews_mentor_id"), "reviews", ["mentor_id"], unique=False
    )
    op.create_index(
        op.f("ix_reviews_reviewed_at"),
        "reviews",
        ["reviewed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reviews_submission_id"),
        "reviews",
        ["submission_id"],
        unique=True,
    )
    op.create_table(
        "sandbox_executions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submissions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sandbox_executions_submission_id"),
        "sandbox_executions",
        ["submission_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sandbox_executions_submission_id"),
        table_name="sandbox_executions",
    )
    op.drop_table("sandbox_executions")
    op.drop_index(op.f("ix_reviews_submission_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_reviewed_at"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_mentor_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(
        op.f("ix_answer_options_question_id"), table_name="answer_options"
    )
    op.drop_table("answer_options")
    op.drop_index(op.f("ix_submissions_user_id"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_task_id"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_status"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_created_at"), table_name="submissions")
    op.drop_table("submissions")
    op.drop_index(op.f("ix_questions_task_id"), table_name="questions")
    op.drop_index(op.f("ix_questions_order"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_code_tasks_task_id"), table_name="code_tasks")
    op.drop_table("code_tasks")
    op.drop_index(op.f("ix_tasks_lesson_id"), table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
