"""sandbox_updated

Revision ID: 301d0bf8797e
Revises: 24ec7a0cd71f
Create Date: 2026-03-30 19:14:24.852626

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "301d0bf8797e"
down_revision: Union[str, Sequence[str], None] = "24ec7a0cd71f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sandbox_executions_submission_id"),
        table_name="sandbox_executions",
    )
    op.drop_table("sandbox_executions")
    op.drop_column("code_tasks", "tests_definition")
    op.drop_column("code_tasks", "template_code")
    op.drop_column("code_tasks", "time_limit")
    op.drop_column("code_tasks", "memory_limit")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "code_tasks",
        sa.Column(
            "memory_limit", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "code_tasks",
        sa.Column(
            "time_limit", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "code_tasks",
        sa.Column(
            "template_code", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "code_tasks",
        sa.Column(
            "tests_definition",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_table(
        "sandbox_executions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "submission_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "result",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("sandbox_executions_submission_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sandbox_executions_pkey")),
    )
    op.create_index(
        op.f("ix_sandbox_executions_submission_id"),
        "sandbox_executions",
        ["submission_id"],
        unique=True,
    )
    # ### end Alembic commands ###
