"""score fix

Revision ID: aa023782dda1
Revises: 301d0bf8797e
Create Date: 2026-04-03 10:11:54.722711

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa023782dda1"
down_revision: Union[str, Sequence[str], None] = "301d0bf8797e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submissions", "max_score")
    op.add_column(
        "tasks",
        sa.Column("max_score", sa.Integer(), nullable=False, server_default="5"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "max_score")
    op.add_column(
        "submissions",
        sa.Column("max_score", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
