map $http_referer $service_name {
    ~/api/users/ users-service:8000;
    ~/api/courses/ courses-service:8000;
    ~/api/tasks/ tasks-service:8000;
    default "";
}

server {
    listen 80;
    server_name localhost;

    # API Users
    location /api/users/ {
        # Убираем /api/users из пути при передаче в сервис
        rewrite ^/api/users/(.*) /$1 break;

        proxy_pass http://users-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # API Courses
    location /api/courses/ {
        rewrite ^/api/courses/(.*) /$1 break;

        proxy_pass http://courses-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # API Tasks
    location /api/tasks/ {
        rewrite ^/api/tasks/(.*) /$1 break;

        proxy_pass http://tasks-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~ ^/(openapi.json|api/v1/schema/|swagger/|redoc/) {
        if ($service_name != "") {
            proxy_pass http://$service_name$request_uri;
            break;
        }
        return 404;
    }

    # # Frontend
    # location / {
    #     proxy_pass http://frontend:3000/;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    # }

    # Health check
    location /health {
        return 200 "API Gateway is running!\n";
        add_header Content-Type text/plain;
    }
}